### ISSUE TITLE
Make log table more universal and extensible

### ISSUE THREAD

**Issue by leechwort** [hacklabkyiv/prismo#7]
Now we have very specific log table in our database, onle start and stop invents are allowed. I propose use such structure instead:
text: user_key(can be None)
text: user_id
text: device_id
text:operation(lock, unlock, device connection, firmware updated, succesfull setup, etc.)
int: time

**Comment by VovaStelmashchuk** [comment]
I think the word 'logs' may not be the best fit for the table 'work_logs.' I designed the table to serve as a storage of information about tool usage, such as drilling machines and lathes.

I agree with your point that the current solution is not sufficient for storing all the information about devices, firmware, etc. My suggestion is to keep 'work_logs' as it is and use this table exclusively for storing data about using instrument tools. For common logs and other types of information, we can create a separate solution.

**Comment by leechwort** [comment]
I am not sure that we need so many table entities for this task. Task is logging, we can store there logs and easily filter needed values by simple requests.

**Comment by VovaStelmashchuk** [comment]
Ok, I caught you point. 

Check the the following, to be sure we are on the same page:

### A reader control access to tools:
Current solution:
The user unlocks the reader, Prismo creates a new record into the `work_logs` table. 
The user locks the reader, Prismo updates an exist record.

In your scenario:
The user unlocks the reader, Prismo creates a new record with the type 'unlock'
The user locks the reader, Prismo creates one more record with the type 'lock'

### A reader control access to a door or a lock
Prismo just adds a new record with the type `open`

In case we are on the same page, I agree with your suggestion, modify the work_logs table. Maybe with a new name, `event_log` - for instance. Be keep consistency with the data and the table name. 


One more point: Why do we need to store both value: `user_id` and `user_key`, looks like a data duplication, we already have dependencies for the field in user tables.

**Comment by leechwort** [comment]
Yup, this is what I meant.

Regarding user_id and user_key - as we still need to add new users, currently we use log entry of user_key, but user_id is unknown. But yes, maybe id is not necessary, yes
